const replacements: Array<[RegExp, string]> = [
  [/\?¢/g, "•"],
  [/\?-n/g, "Ön"],
  [/\?-nerilen/g, "Önerilen"],
  [/\?-zet/g, "Özet"],
  [/G\?bre/g, "Gübre"],
  [/Gran\?lasyon/g, "Granülasyon"],
  [/Gran\?l/g, "Granül"],
  [/Atik/g, "Atık"],
  [/Atik Su \?amuru ve Aritma \?z\?mleri/g, "Atık Su Çamuru ve Arıtma Çözümleri"],
  [/\?amuru/g, "Çamuru"],
  [/\?amur/g, "Çamur"],
  [/Aritma/g, "Arıtma"],
  [/\?z\?mleri/g, "Çözümleri"],
  [/\?z\?m\?/g, "çözümü"],
  [/\?z\?m/g, "çözüm"],
  [/D\?n\?\?m/g, "Dönüşüm"],
  [/Y\?netimi/g, "Yönetimi"],
  [/Y\?netim/g, "Yönetim"],
  [/I\?Yleme/g, "İşleme"],
  [/D\?kme/g, "Dökme"],
  [/Kati/g, "Katı"],
  [/t\?m/g, "tüm"],
  [/T\?m/g, "Tüm"],
  [/s\?reci/g, "süreci"],
  [/S\?reci/g, "Süreci"],
  [/s\?re\?lerde/g, "süreçlerde"],
  [/s\?re\?leri/g, "süreçleri"],
  [/s\?re\?/g, "süreç"],
  [/S\?re\?/g, "Süreç"],
  [/y\?net/g, "yönet"],
  [/m\?hendislik/g, "mühendislik"],
  [/M\?hendislik/g, "Mühendislik"],
  [/i\?in/g, "için"],
  [/\?zel/g, "özel"],
  [/\?ng\?r\?lebilir/g, "öngörülebilir"],
  [/\?Yekilde/g, "şekilde"],
  [/a\?Yama/g, "aşama"],
  [/sa\?Ylar/g, "sağlar"],
  [/sa\?Ylariz/g, "sağlarız"],
  [/ko\?Yullari/g, "koşulları"],
  [/ko\?Yullarina/g, "koşullarına"],
  [/de\?Yerlendirilir/g, "değerlendirilir"],
  [/de\?Yi\?Yir/g, "değişir"],
  [/de\?Yi\?Yiklik/g, "değişiklik"],
  [/de\?Yi\?Yimi/g, "değişimi"],
  [/olu\?Yturulur/g, "oluşturulur"],
  [/olu\?Yturma/g, "oluşturma"],
  [/olu\?Yturalim/g, "oluşturalım"],
  [/olu\?Yabilecek/g, "oluşabilecek"],
  [/netle\?Ytirilir/g, "netleştirilir"],
  [/\?retim/g, "üretim"],
  [/\?retilir/g, "üretilir"],
  [/\?oretilen/g, "Üretilen"],
  [/\?oretilecek/g, "Üretilecek"],
  [/\?mr\?n/g, "ömrün"],
  [/\?m\?rl\?/g, "ömürlü"],
  [/\?l\?lerde/g, "ölçülerde"],
  [/\?l\?lebilir/g, "ölçülebilir"],
  [/\?l\?l?r/g, "ölçülür"],
  [/\?ali\?Yir/g, "çalışır"],
  [/\?ali\?Yma/g, "çalışma"],
  [/\?ali\?Ymasini/g, "çalışmasını"],
  [/\?ali\?Ytirilir/g, "çalıştırılır"],
  [/\?ali\?Ytirma/g, "çalıştırma"],
  [/\?ali\?Yacak/g, "çalışacak"],
  [/E\?Yitim/g, "Eğitim"],
  [/e\?Yitim/g, "eğitim"],
  [/Sati\?Y/g, "Satış"],
  [/m\?Yteri/g, "müşteri"],
  [/M\?mk?n/g, "Mümkün"],
  [/a\?Yir/g, "ağır"],
  [/D\?Y\?k/g, "Düşük"],
  [/b\?t\?nle\?Yik/g, "bütünleşik"],
  [/Ta\?ma/g, "Taşıma"],
  [/konvey\?r/g, "konveyör"],
  [/elevat\?r/g, "elevatör"],
  [/par\?alayici/g, "parçalayıcı"],
  [/par\?alayicilar/g, "parçalayıcılar"],
  [/Reakt\?r/g, "Reaktör"],
  [/kari\?Ytirma/g, "karıştırma"],
  [/Operat\?r/g, "Operatör"],
  [/g\?venli/g, "güvenli"],
  [/g\?venlik/g, "güvenlik"],
  [/d\?zenli/g, "düzenli"],
  [/y\?ksek/g, "yüksek"],
  [/d\?r\?r/g, "dürür"],
  [/d\?Y\?r\?r/g, "düşürür"],
  [/g\?l\?/g, "güçlü"],
  [/kavu\?Yur/g, "kavuşur"],
  [/ge\?i\?Y/g, "geçiş"],
  [/\?nleyici/g, "önleyici"],
  [/\?nlenir/g, "önlenir"],
  [/Kütüphaneye Dön/g, "Kütüphaneye Dön"],
  [/Ilgili icerikler/g, "İlgili içerikler"],
  [/Ilgili i?erikler/g, "İlgili içerikler"],
  [/Ilgili alt basliklar/g, "İlgili alt başlıklar"],
  [/Uzmanlik Kapsami/g, "Uzmanlık Kapsamı"],
  [/Bu Hizmet Size Ne Sağlar\?/g, "Bu Hizmet Size Ne Sağlar?"],
  [/Bu Hizmet Size Ne Sa\?Ylar\?/g, "Bu Hizmet Size Ne Sağlar?"],
  [/Nasil çalışiyoruz\?/g, "Nasıl çalışıyoruz?"],
  [/Nasil \?ali\?Yiyoruz\?/g, "Nasıl çalışıyoruz?"],
  [/Sik Sorulan Sorular/g, "Sık Sorulan Sorular"],
  [/Tum Cozum Alanlarina Don/g, "Tüm Çözüm Alanlarına Dön"],
  [/Detayi Incele/g, "Detayı İncele"],
  [/Cozumler/g, "Çözümler"],
  [/Cozumu/g, "Çözümü"],
  [/Cozum/g, "Çözüm"],
  [/Sektorlere/g, "Sektörlere"],
  [/Sektorler/g, "Sektörler"],
  [/Sektor/g, "Sektör"],
  [/Gubre/g, "Gübre"],
  [/Granulasyon/g, "Granülasyon"],
  [/Granul/g, "Granül"],
  [/Donusumleri/g, "Dönüşümleri"],
  [/Donusumu/g, "Dönüşümü"],
  [/Donusumde/g, "Dönüşümde"],
  [/Donusumun/g, "Dönüşümün"],
  [/Donustur/g, "Dönüştür"],
  [/Donusum/g, "Dönüşüm"],
  [/Donus/g, "Dönüş"],
  [/Atik/g, "Atık"],
  [/Camuru/g, "Çamuru"],
  [/Camur/g, "Çamur"],
  [/Aritma/g, "Arıtma"],
  [/Dokme/g, "Dökme"],
  [/Kati/g, "Katı"],
  [/Muhendisligi/g, "Mühendisliği"],
  [/Muhendislik/g, "Mühendislik"],
  [/Muhendisi/g, "Mühendisi"],
  [/Iletisim/g, "İletişim"],
  [/Kutuphane/g, "Kütüphane"],
  [/Kutuphaneye/g, "Kütüphaneye"],
  [/Hakkimizda/g, "Hakkımızda"],
  [/Gorusme/g, "Görüşme"],
  [/Goruntuleme/g, "Görüntüleme"],
  [/Goruntule/g, "Görüntüle"],
  [/Gorselleri/g, "Görselleri"],
  [/Gorseller/g, "Görseller"],
  [/Gorsel/g, "Görsel"],
  [/Yonetimi/g, "Yönetimi"],
  [/Yonetim/g, "Yönetim"],
  [/Calismalari/g, "Çalışmaları"],
  [/Calisma/g, "Çalışma"],
  [/Calisir/g, "Çalışır"],
  [/Calisir\?/g, "Çalışır?"],
  [/Cagri/g, "Çağrı"],
  [/Cekicli/g, "Çekiçli"],
  [/Ceneli/g, "Çeneli"],
  [/Kirici/g, "Kırıcı"],
  [/Tasima/g, "Taşıma"],
  [/tasima/g, "taşıma"],
  [/Isletme/g, "İşletme"],
  [/Isleme/g, "İşleme"],
  [/Ilgili/g, "İlgili"],
  [/Inceleyin/g, "İnceleyin"],
  [/Incele/g, "İncele"],
  [/Taniyin/g, "Tanıyın"],
  [/Tani/g, "Tanı"],
  [/Turkiye/g, "Türkiye"],
  [/Satis/g, "Satış"],
  [/Ozel/g, "Özel"],
  [/Olcek/g, "Ölçek"],
  [/olcek/g, "ölçek"],
  [/Surdur/g, "Sürdür"],
  [/Surecleri/g, "Süreçleri"],
  [/Sureclerde/g, "Süreçlerde"],
  [/sureci/g, "süreci"],
  [/surec/g, "süreç"],
  [/Sureci/g, "Süreci"],
  [/Surec/g, "Süreç"],
  [/uretim/g, "üretim"],
  [/Uretim/g, "Üretim"],
  [/Uretimi/g, "Üretimi"],
  [/Urun/g, "Ürün"],
  [/urun/g, "ürün"],
  [/Diger/g, "Diğer"],
  [/Cerez/g, "Çerez"],
  [/Kisa/g, "Kısa"],
  [/Ozeti/g, "Özeti"],
  [/Sonuc/g, "Sonuç"],
  [/kazanim/g, "kazanım"],
  [/Kazanim/g, "Kazanım"],
  [/degil/g, "değil"],
  [/Degil/g, "Değil"],
  [/dogru/g, "doğru"],
  [/Dogru/g, "Doğru"],
  [/yon/g, "yön"],
  [/Yon/g, "Yön"],
  [/guven/g, "güven"],
  [/Guven/g, "Güven"],
  [/buyu/g, "büyü"],
  [/Buyu/g, "Büyü"],
  [/cok/g, "çok"],
  [/Cok/g, "Çok"],
  [/ustu/g, "üstü"],
  [/Ustu/g, "Üstü"],
  [/alti/g, "altı"],
  [/Gundelik/g, "Gündelik"],
  [/gundelik/g, "gündelik"],
  [/E-posta Gonder/g, "E-posta Gönder"],
  [/Hemen Ara/g, "Hemen Ara"],
];

const mojibakeMap: Record<string, string> = {
  "Ã‡": "Ç",
  "Ã§": "ç",
  "ÄŸ": "ğ",
  "Äž": "Ğ",
  "Ä±": "ı",
  "Ä°": "İ",
  "Ã¶": "ö",
  "Ã–": "Ö",
  "ÅŸ": "ş",
  "Åž": "Ş",
  "Ã¼": "ü",
  "Ãœ": "Ü",
};

export function trText(text: string): string {
  let value = text;

  for (const [broken, fixed] of Object.entries(mojibakeMap)) {
    value = value.split(broken).join(fixed);
  }

  return replacements.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), value);
}
