import type { MetadataRoute } from "next";
import { compostSystemDetailMap } from "./lib/compost-system-detail-data";
import { dryingSystemDetailMap } from "./lib/drying-system-detail-data";
import { drumSystemDetailMap } from "./lib/drum-system-detail-data";
import { fertilizerSystemDetailMap } from "./lib/fertilizer-system-detail-data";
import { liquidFertilizerDetailMap } from "./lib/liquid-fertilizer-detail-data";
import { topicalBlogDynamicSlugs } from "./lib/topical-authority-blog-data";

const siteUrl = "https://www.promakina.com.tr";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  const dynamicBlogRoutes = Array.from(
    new Set([
      ...topicalBlogDynamicSlugs,
      "granulator-tamburu-secimi",
      ...Object.keys(compostSystemDetailMap),
      ...Object.keys(drumSystemDetailMap),
      ...Object.keys(dryingSystemDetailMap),
      ...Object.keys(fertilizerSystemDetailMap),
      ...Object.keys(liquidFertilizerDetailMap),
    ]),
  ).map((slug) => ({
    url: `${siteUrl}/kutuphane/blog/${slug}`,
    lastModified,
    changeFrequency: "weekly" as const,
    priority: 0.8,
  }));

  return [
    {
      url: `${siteUrl}/`,
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${siteUrl}/hizmetler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/gubre-tesisi-kurulumu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/kurutma-tamburu-imalati`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/camur-kurutma-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/silis-kumu-kurutma-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/maden-kurutma-ve-eleme-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/organomineral-gubre-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/granul-gubre-uretim-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/kompost-tesisi-kurulumu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/hizmetler/sivi-gubre-uretim-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/makinalar-ekipman`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tasima-ekipmanlari`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/eleme-ve-siniflandirma-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/toz-toplama-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/paketleme-ve-dolum-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/reaktorler-ve-tanklar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/dozajlama-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/depolama-ve-besleme-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/yardimci-ekipmanlar-ve-akis-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/sektorler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${siteUrl}/projeler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/evsel-atiklardan-kompost-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/hayvansal-atiklardan-kompost-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/tarimsal-atiklardan-kompost-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/1mw-biyogaz-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/biyogaz-digestat-kurutma-kompost-projesi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/10-ton-saat-organomineral-gubre-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/granul-gubre-uretim-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/sivi-gubre-uretim-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/silis-kumu-kurutma-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/perlit-kurutma-eleme-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/maden-kirma-eleme-kurutma-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/aritma-camuru-kurutma-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/deri-atiklarindan-geri-kazanim-tesisi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/helezon-konveyor-elevator-hat-projesi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/reaktor-ve-tank-sistemleri-projesi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/projeler/ozel-proses-ve-makine-imalati-projesi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/iletisim`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/hakkimizda`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/kariyer`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tasima-ekipmanlari/vidali-helezonlar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tasima-ekipmanlari/bantli-konveyorler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tasima-ekipmanlari/zincirli-elevatorler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/granulator-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/kurutma-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/sogutma-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/kompost-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/kaplama-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/karistirma-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/sterilizasyon-ve-stabilizasyon-tamburu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/tambur-sistemleri/ozel-tambur`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/eleme-ve-siniflandirma-sistemleri/trommel-elekler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/cekicli-kiricilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/shredder-sistemleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/dik-milli-kiricilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/ceneli-kiricilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/bicakli-primer-kiricilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/kiricilar-ve-parcalayicilar/zincirli-kiricilar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/depolama-ve-besleme-sistemleri/bunker-ve-hazneler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/yardimci-ekipmanlar-ve-akis-sistemleri/yukleme-korugu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/yardimci-ekipmanlar-ve-akis-sistemleri/distributor`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/yardimci-ekipmanlar-ve-akis-sistemleri/klapeler`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/dozajlama-sistemleri/mikro-dozajlama`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/dozajlama-sistemleri/makro-dozajlama`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/makinalar-ekipman/dozajlama-sistemleri/dozaj-bant-kantari`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/sektorler/atik-su-camuru-ve-aritma-cozumleri/kapali-sistem-camur-kurutma`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/sektorler/atik-su-camuru-ve-aritma-cozumleri/acik-sistem-camur-kurutma`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/sektorler/atik-su-camuru-ve-aritma-cozumleri/atik-su-camurundan-aty-hazirlama`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/sektorler/atik-su-camuru-ve-aritma-cozumleri/atik-su-camurundan-kompost-uretimi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/sektorler/kompost-ve-organik-atik-tesisleri/evsel-organik-atiklar`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/sektorler/enerji-ve-biyogaz-sistemleri/tarimsal-atik-biyogaz-tesisleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/kutuphane/organomineral-gubre-tesisi-maliyeti`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/kutuphane/organik-atiklarin-geri-kazanimi`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/kutuphane/blog`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/kutuphane/granul-gubre-uretim-sureci`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/kutuphane/sivi-gubre-uretim-tesisi-nasil-kurulur`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/kutuphane/kurutma-tamburu-tasarim-kriterleri`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/kutuphane/sik-sorulan-sorular`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/kutuphane/terimler-sozlugu`,
      lastModified,
      changeFrequency: "weekly",
      priority: 0.7,
    },
    ...dynamicBlogRoutes,
  ];
}
